### ISSUE TITLE
MYMETA should not be included

### ISSUE THREAD

**Issue by chorny** [tokubass/p5-EPUB-Parser#2]
Your distribution (TOKUBASS/EPUB-Parser-0.05.tar.gz) contains files MYMETA.yml and/or MYMETA.json. These files should not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is about old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=TOKUBASS and contact me.

**Comment by tokubass** [comment]
thank you for reporting.
I will try it.
