### ISSUE TITLE
Seems to have dependency on XML::SAX::Exception

### ISSUE THREAD

**Issue by benkasminbullock** [tokubass/p5-EPUB-Parser#3]
The module seems to depend on XML::SAX::Exception and won't install without it, but this doesn't seem to be a registered dependency.

**Comment by tokubass** [comment]
no problem.
META.json contain "XML::LibXML" .
Please trace dependency of XML::LibXML.

**Comment by benkasminbullock** [comment]
I checked and it looks like you are correct, so I'll close this.
